var Interpreter;
(()=>{var p={};({726:function(w,q){var e,l=this&&this.__awaiter||function(a,c,d,b){return new (d||=Promise)(function(g,f){function r(k){try{m(b.next(k))}catch(h){f(h)}}function t(k){try{m(b.throw(k))}catch(h){f(h)}}function m(k){var h;k.done?g(k.value):(h=k.value,h instanceof d?h:new d(function(u){u(h)})).then(r,t)}m((b=b.apply(a,c||[])).next())})};Object.defineProperty(q,"__esModule",{value:!0});q.default=class{constructor(){this._registerA=new Uint32Array([0]);this._registerB=new Uint32Array([0]);this._registerR=
new Uint32Array([0]);this._stack=[];this._callStack=[];this._output=a=>{process.stdout.write(a)};this._labels=new Map;this._memoryRegions=new Map}get registerA(){return this._registerA.slice(0)}get registerB(){return this._registerB.slice(0)}get registerR(){return this._registerR.slice(0)}get stack(){return this._stack}get memoryRegions(){return this._memoryRegions}run(a){return l(this,void 0,void 0,function*(){if(yield this.runWithoutStackCheck(a),0!==this.stack.length)throw Error("stack is not empty.");
})}runWithoutStackCheck(a){return l(this,void 0,void 0,function*(){this._instructions=a.split("\n").map(c=>c.replace("\n","").trim());this._ticks=this._programCounter=0;yield this.initExports();this.processLabels();this.processMemoryRegions();this.processInstructions()})}setOutput(a){return l(this,void 0,void 0,function*(){this._output=a})}initExports(){return l(this,void 0,void 0,function*(){var a=new Uint8Array([0,97,115,109,1,0,0,0,1,13,2,96,2,127,127,1,127,96,2,125,125,1,125,3,11,10,0,0,0,0,0,
0,1,1,1,1,7,67,10,3,97,100,100,0,0,3,115,117,98,0,1,3,109,117,108,0,2,3,114,101,109,0,5,4,105,100,105,118,0,3,4,117,100,105,118,0,4,4,102,97,100,100,0,6,4,102,115,117,98,0,7,4,102,109,117,108,0,8,4,102,100,105,118,0,9,10,81,10,7,0,32,0,32,1,106,11,7,0,32,0,32,1,107,11,7,0,32,0,32,1,108,11,7,0,32,0,32,1,109,11,7,0,32,0,32,1,110,11,7,0,32,0,32,1,112,11,7,0,32,0,32,1,146,11,7,0,32,0,32,1,147,11,7,0,32,0,32,1,148,11,7,0,32,0,32,1,149,11]);a=yield WebAssembly.compile(a);this._exports=(yield WebAssembly.instantiate(a,
{})).exports})}getFloatingPointValue(a){if(a instanceof Uint32Array||a instanceof Int32Array)return(new DataView(a.buffer)).getFloat32(0,!0);if(a instanceof Float32Array)return a[0];throw Error("Unknown datatype to convert to floating point value.");}getIntegerValue(a){if(a instanceof Uint32Array||a instanceof Int32Array||a instanceof Float32Array)return(new DataView(a.buffer)).getInt32(0,!0);throw Error("Unknown datatype to convert to floating point value.");}getUnsignedIntegerValue(a){if(a instanceof
Uint32Array||a instanceof Int32Array||a instanceof Float32Array)return(new DataView(a.buffer)).getUint32(0,!0);throw Error("Unknown datatype to convert to floating point value.");}jumpToLocation(a,c){let d=String();switch(c){case e.Operand:a.operand&&(d=a.operand);break;case e.Arg0:a.arg0&&(d=a.arg0);break;case e.Arg1:a.arg1&&(d=a.arg1)}const b=this._labels.get(d);if(this._memoryRegions.get(d))throw a.error(c,"Cannot jump to a memory location.");if(!b)throw a.error(c,"Invalid label location provided.");
this.jumpToLocationByAddress(a,b.lineNumber)}jumpToLocationByAddress(a,c){if(0>c||c>this._instructions.length)throw a.error(e.Operand,"Address is out of bounds.");this._programCounter=c;this._didModifyProgramCounter=!0}getNumericValue(a,c){var d=String();switch(c){case e.Operand:a.operand&&(d=a.operand);break;case e.Arg0:a.arg0&&(d=a.arg0);break;case e.Arg1:a.arg1&&(d=a.arg1)}var b=this._labels.get(d);if(b)return new Uint32Array([b.address]);if(d.endsWith("f")){d=d.replace("f","");d=Number.parseFloat(d);
if(Number.isNaN(d))throw a.error(c,"Invalid floating point value provided.");return new Float32Array([d])}b=Number.parseInt(d);if(d.includes(".")||Number.isNaN(b))throw a.error(c,"Invalid value provided.");return 0>b?new Int32Array([b]):new Uint32Array([b])}getMemoryValue(a,c){var d=String();switch(c){case e.Operand:a.operand&&(d=a.operand);break;case e.Arg0:a.arg0&&(d=a.arg0);break;case e.Arg1:a.arg1&&(d=a.arg1)}d=this._memoryRegions.get(d);if(!d)throw a.error(c,"Invalid memory region provided.");
return d.slice(0)}setMemoryValue(a,c,d){this.setMemoryNumericValue(a,c,this.getNumericValue(a,d))}setMemoryNumericValue(a,c,d){let b=String();switch(c){case e.Operand:a.operand&&(b=a.operand);break;case e.Arg0:a.arg0&&(b=a.arg0);break;case e.Arg1:a.arg1&&(b=a.arg1)}if(!this._memoryRegions.get(b))throw a.error(c,"Invalid memory region provided.");this._memoryRegions.set(b,d.slice(0))}setMemoryNumericValueByAddress(a,c,d){let b;if(this._labels.forEach((g,f)=>{g.address===c&&(b=f)}),!b)throw a.error(e.Operand,
"Unable to resolve line number to a label.");if(!this._memoryRegions.get(b))throw a.error(e.Operand,"The corresponding address does not corresponding to a given memory region (buffer overrun?).");this._memoryRegions.set(b,d.slice(0))}getMemoryNumericValueByAddress(a,c){let d;if(this._labels.forEach((g,f)=>{g.address===c&&(d=f)}),!d)throw a.error(e.Operand,"Unable to resolve line number to a label.");const b=this._memoryRegions.get(d);if(b)return b;throw a.error(e.Operand,"The corresponding address does not corresponding to a given memory region (buffer overrun?).");
}pushMemory(a,c){a=this.getMemoryValue(a,c);this._stack.push(a.slice(0))}pushNumericValue(a,c){a=this.getNumericValue(a,c);this._stack.push(a.slice(0))}moveValue(a,c,d){d=this._stack[c];c=this._stack.splice(c,1);if(!d||0>=c.length)throw a.error(e.Operand,"Stack was immovable.");this.pushValue(a,d)}pushValue(a,c){this._stack.push(c.slice(0))}popValue(a){const c=this._stack.pop();if(!c)throw a.error(e.Operand,"Stack was empty.");return c.slice(0)}processMemoryRegions(){this._labels.forEach((a,c)=>{a.lineNumber in
this._instructions&&(a=new n(this._instructions[a.lineNumber],a.lineNumber),a.arg0&&".data"===a.operand&&this._memoryRegions.set(c,this.getNumericValue(a,e.Arg0)))})}processLabels(){let a=0;for(let c=0;c<this._instructions.length;c++){const d=this._instructions[c],b=new n(d,c);"HALT"===b.operand||"GETAVB"===b.operand||"GETA"===b.operand||"GETB"===b.operand||"VGETA"===b.operand||"VGETB"===b.operand||"PUSH"===b.operand||"VPUSH"===b.operand||"SAVEPUSH"===b.operand||"SAVEPUSHA"===b.operand||"SAVEPUSHB"===
b.operand||"SAVEFRONT"===b.operand||"MOVOUTPUSH"===b.operand||"POP"===b.operand||"GETPOPA"===b.operand||"GETPOPB"===b.operand||"GETPOPR"===b.operand||"POPNOP"===b.operand||"MOVINPOP"===b.operand||"SAVE"===b.operand||"SAVEA"===b.operand||"SAVEB"===b.operand||"SAVETOA"===b.operand||"SAVETOB"===b.operand||"JA"===b.operand||"JNA"===b.operand||"JMP"===b.operand||"CALL"===b.operand||"RTN"===b.operand||"MOV"===b.operand||"MOVIN"===b.operand||"MOVOUT"===b.operand||"ADD"===b.operand||"FADD"===b.operand||"SADD"===
b.operand||"MULT"===b.operand||"FMULT"===b.operand||"SMULT"===b.operand||"DIV"===b.operand||"FDIV"===b.operand||"SDIV"===b.operand||"SUB"===b.operand||"FSUB"===b.operand||"SSUB"===b.operand||"CMPE"===b.operand||"CMPNE"===b.operand||"CMPLT"===b.operand||"CMPLTE"===b.operand||"CMPGT"===b.operand||"CMPGTE"===b.operand||"SCMPE"===b.operand||"SCMPNE"===b.operand||"SCMPLT"===b.operand||"SCMPLTE"===b.operand||"SCMPGT"===b.operand||"SCMPGTE"===b.operand||"FCMPE"===b.operand||"FCMPNE"===b.operand||"FCMPLT"===
b.operand||"FCMPLTE"===b.operand||"FCMPGT"===b.operand||"FCMPGTE"===b.operand||"NEG"===b.operand||"SNEG"===b.operand||"FNEG"===b.operand||"INC"===b.operand||"DEC"===b.operand||"FINC"===b.operand||"FDEC"===b.operand||"REM"===b.operand||"AND"===b.operand||"SHIFTL"===b.operand||"SHIFTR"===b.operand||"OR"===b.operand||"XOR"===b.operand||"NOT"===b.operand||"FLTOINT"===b.operand||"INTTOFL"===b.operand||"LAND"===b.operand||"LOR"===b.operand||"QADD"===b.operand||"QSUB"===b.operand||"QLADD"===b.operand||"QLSUB"===
b.operand||"QSTORE"===b.operand||"TICK"===b.operand||"RAND"===b.operand||"PRINT"===b.operand||".data"===b.operand?a+=1:"STORE"===b.operand||"STOREPUSH"===b.operand?a+=2:d.endsWith(":")&&this._labels.set(d.replace(":",""),new v(a,c+1))}}processInstructions(){for(;;){const a=new n(this._instructions[this._programCounter],this._programCounter);if(this._didModifyProgramCounter=!1,this._ticks++,a.operand){if("HALT"===a.operand)break;if("GETA"===a.operand||"GETB"===a.operand||"VGETA"===a.operand||"VGETB"===
a.operand)this.interpretGET(a);else if("PUSH"===a.operand||"VPUSH"===a.operand||"SAVEPUSH"===a.operand||"SAVEPUSHA"===a.operand||"SAVEPUSHB"===a.operand||"SAVEFRONT"===a.operand||"MOVOUTPUSH"===a.operand||"STOREPUSH"===a.operand)this.interpretPUSH(a);else if("POP"===a.operand||"GETPOPA"===a.operand||"GETPOPB"===a.operand||"GETPOPR"===a.operand||"POPNOP"===a.operand||"MOVINPOP"===a.operand)this.interpretPOP(a);else if("SAVE"===a.operand||"SAVEA"===a.operand||"SAVEB"===a.operand||"SAVETOA"===a.operand||
"SAVETOB"===a.operand)this.interpretSAVE(a);else if("JA"===a.operand||"JNA"===a.operand||"JMP"===a.operand||"CALL"===a.operand||"RTN"===a.operand)this.interpretJUMP(a);else if("MOV"===a.operand||"MOVIN"===a.operand||"MOVOUT"===a.operand)this.interpretMOVE(a);else if("ADD"===a.operand||"FADD"===a.operand||"SADD"===a.operand||"MULT"===a.operand||"FMULT"===a.operand||"SMULT"===a.operand||"DIV"===a.operand||"FDIV"===a.operand||"SDIV"===a.operand||"SUB"===a.operand||"FSUB"===a.operand||"SSUB"===a.operand||
"CMPE"===a.operand||"CMPNE"===a.operand||"CMPLT"===a.operand||"CMPLTE"===a.operand||"CMPGT"===a.operand||"CMPGTE"===a.operand||"SCMPE"===a.operand||"SCMPNE"===a.operand||"SCMPLT"===a.operand||"SCMPLTE"===a.operand||"SCMPGT"===a.operand||"SCMPGTE"===a.operand||"FCMPE"===a.operand||"FCMPNE"===a.operand||"FCMPLT"===a.operand||"FCMPLTE"===a.operand||"FCMPGT"===a.operand||"FCMPGTE"===a.operand||"NEG"===a.operand||"SNEG"===a.operand||"FNEG"===a.operand||"INC"===a.operand||"DEC"===a.operand||"FINC"===a.operand||
"FDEC"===a.operand||"REM"===a.operand||"AND"===a.operand||"SHIFTL"===a.operand||"SHIFTR"===a.operand||"OR"===a.operand||"XOR"===a.operand||"NOT"===a.operand||"FLTOINT"===a.operand||"INTTOFL"===a.operand||"LAND"===a.operand||"LOR"===a.operand)this.interpretCOMPUTE(a);else if("QADD"===a.operand||"QSUB"===a.operand||"QLADD"===a.operand||"QLSUB"===a.operand||"QSTORE"===a.operand||"STORE"===a.operand)this.interpretSTORE(a);else if("TICK"===a.operand||"RAND"===a.operand||"PRINT"===a.operand||"GETAVB"===
a.operand)this.interpretSPECIAL(a);else if("#"!==a.operand&&!this._instructions[this._programCounter].endsWith(":"))throw a.error(e.Operand,"Unimplemented instruction '"+a.operand+"'.");}this._didModifyProgramCounter||this._programCounter++}}interpretGET(a){var c,d,b;let g;g=(null===(c=a.operand)||void 0===c?0:c.startsWith("V"))?this.getNumericValue(a,e.Arg0):this.getMemoryValue(a,e.Arg0);(null===(d=a.operand)||void 0===d?0:d.endsWith("A"))?this._registerA=g:(null===(b=a.operand)||void 0===b?0:b.endsWith("B"))?
this._registerB=g:a.error(e.Operand,"Unknown operand for GET-like instruction.")}interpretPUSH(a){if("PUSH"===a.operand)this.pushMemory(a,e.Arg0);else if("VPUSH"===a.operand||"STOREPUSH"===a.operand)this.pushNumericValue(a,e.Arg0);else if("SAVEPUSH"===a.operand)this.pushValue(a,this._registerR);else if("SAVEPUSHA"===a.operand)this.pushValue(a,this._registerA);else if("SAVEPUSHB"===a.operand)this.pushValue(a,this._registerB);else if("SAVEFRONT"===a.operand)this.moveValue(a,this._stack.length-1-Number(a.arg0),
this._stack.length-1);else if("MOVOUTPUSH"===a.operand){var c=(new Uint32Array(this._registerR))[0];c=this.getMemoryNumericValueByAddress(a,c);this.pushValue(a,c)}else a.error(e.Operand,"Unknown operand for PUSH-like instruction.")}interpretPOP(a){var c=this.popValue(a);"POP"===a.operand?this.setMemoryNumericValue(a,e.Arg0,c):"GETPOPA"===a.operand?this._registerA=c:"GETPOPB"===a.operand?this._registerB=c:"GETPOPR"===a.operand?this._registerR=c:"MOVINPOP"===a.operand?(c=(new Uint32Array(c))[0],this.setMemoryNumericValueByAddress(a,
c,this._registerR)):"POPNOP"===a.operand||a.error(e.Operand,"Unknown operand for POP-like instruction.")}interpretSAVE(a){"SAVE"===a.operand?this.setMemoryNumericValue(a,e.Arg0,this._registerR):"SAVEA"===a.operand?this.setMemoryNumericValue(a,e.Arg0,this._registerA):"SAVEB"===a.operand?this.setMemoryNumericValue(a,e.Arg0,this._registerB):"SAVETOA"===a.operand?this._registerA=this.registerR.slice(0):"SAVETOB"===a.operand?this._registerB=this.registerR.slice(0):a.error(e.Operand,"Unknown operand for SAVE-like instruction.")}interpretJUMP(a){if("JA"===
a.operand)0!=this.getUnsignedIntegerValue(this._registerA)&&this.jumpToLocation(a,e.Arg0);else if("JNA"===a.operand)0==this.getUnsignedIntegerValue(this._registerA)&&this.jumpToLocation(a,e.Arg0);else if("JMP"===a.operand)this.jumpToLocation(a,e.Arg0);else if("RTN"===a.operand){const c=this._callStack.pop();if(!c)throw a.error(e.Operand,"Call stack is empty.");this.jumpToLocationByAddress(a,c)}else"CALL"===a.operand?(this._callStack.push(this._programCounter+1),this.jumpToLocation(a,e.Arg0)):a.error(e.Operand,
"Unknown operand for JUMP-like instruction.")}interpretMOVE(a){if("MOV"===a.operand)this.setMemoryNumericValue(a,e.Arg1,this.getMemoryValue(a,e.Arg0));else if("MOVIN"===a.operand){var c=this.getMemoryValue(a,e.Arg0);const d=(new Uint32Array(this._registerR))[0];this.setMemoryNumericValueByAddress(a,d,c)}else"MOVOUT"===a.operand?(c=this.getMemoryNumericValueByAddress(a,(new Uint32Array(this._registerR))[0]),this.setMemoryNumericValue(a,e.Arg0,c)):a.error(e.Operand,"Unknown operand for MOVE-like instruction.")}interpretCOMPUTE(a){"SADD"===
a.operand?this._registerR=new Int32Array([this._exports.add(this.getIntegerValue(this._registerA),this.getIntegerValue(this._registerB))]):"FADD"===a.operand?this._registerR=new Float32Array([this._exports.fadd(this.getFloatingPointValue(this._registerA),this.getFloatingPointValue(this._registerB))]):"ADD"===a.operand?this._registerR=new Uint32Array([this._exports.add(this.getUnsignedIntegerValue(this._registerA),this.getUnsignedIntegerValue(this._registerB))]):"SSUB"===a.operand?this._registerR=
new Int32Array([this._exports.sub(this.getIntegerValue(this._registerA),this.getIntegerValue(this._registerB))]):"FSUB"===a.operand?this._registerR=new Float32Array([this._exports.fsub(this.getFloatingPointValue(this._registerA),this.getFloatingPointValue(this._registerB))]):"SUB"===a.operand?this._registerR=new Uint32Array([this._exports.sub(this.getUnsignedIntegerValue(this._registerA),this.getUnsignedIntegerValue(this._registerB))]):"SDIV"===a.operand?this._registerR=new Int32Array([this._exports.idiv(this.getIntegerValue(this._registerA),
this.getIntegerValue(this._registerB))]):"FDIV"===a.operand?this._registerR=new Float32Array([this._exports.fdiv(this.getFloatingPointValue(this._registerA),this.getFloatingPointValue(this._registerB))]):"DIV"===a.operand?this._registerR=new Uint32Array([this._exports.udiv(this.getUnsignedIntegerValue(this._registerA),this.getUnsignedIntegerValue(this._registerB))]):"SMULT"===a.operand?this._registerR=new Int32Array([this._exports.mul(this.getIntegerValue(this._registerA),this.getIntegerValue(this._registerB))]):
"FMULT"===a.operand?this._registerR=new Float32Array([this._exports.fmul(this.getFloatingPointValue(this._registerA),this.getFloatingPointValue(this._registerB))]):"MULT"===a.operand?this._registerR=new Uint32Array([this._exports.mul(this.getUnsignedIntegerValue(this._registerA),this.getUnsignedIntegerValue(this._registerB))]):"CMPE"===a.operand?this._registerR=new Uint32Array([this.getUnsignedIntegerValue(this._registerA)==this.getUnsignedIntegerValue(this._registerB)?1:0]):"CMPNE"===a.operand?this._registerR=
new Uint32Array([this.getUnsignedIntegerValue(this._registerA)!=this.getUnsignedIntegerValue(this._registerB)?1:0]):"CMPGT"===a.operand?this._registerR=new Uint32Array([this.getUnsignedIntegerValue(this._registerA)>this.getUnsignedIntegerValue(this._registerB)?1:0]):"CMPGTE"===a.operand?this._registerR=new Uint32Array([this.getUnsignedIntegerValue(this._registerA)>=this.getUnsignedIntegerValue(this._registerB)?1:0]):"CMPLT"===a.operand?this._registerR=new Uint32Array([this.getUnsignedIntegerValue(this._registerA)<
this.getUnsignedIntegerValue(this._registerB)?1:0]):"CMPLTE"===a.operand?this._registerR=new Uint32Array([this.getUnsignedIntegerValue(this._registerA)<=this.getUnsignedIntegerValue(this._registerB)?1:0]):"SCMPE"===a.operand?this._registerR=new Uint32Array([this.getIntegerValue(this._registerA)==this.getIntegerValue(this._registerB)?1:0]):"SCMPNE"===a.operand?this._registerR=new Uint32Array([this.getIntegerValue(this._registerA)!=this.getIntegerValue(this._registerB)?1:0]):"SCMPGT"===a.operand?this._registerR=
new Uint32Array([this.getIntegerValue(this._registerA)>this.getIntegerValue(this._registerB)?1:0]):"SCMPGTE"===a.operand?this._registerR=new Uint32Array([this.getIntegerValue(this._registerA)>=this.getIntegerValue(this._registerB)?1:0]):"SCMPLT"===a.operand?this._registerR=new Uint32Array([this.getIntegerValue(this._registerA)<this.getIntegerValue(this._registerB)?1:0]):"SCMPLTE"===a.operand?this._registerR=new Uint32Array([this.getIntegerValue(this._registerA)<=this.getIntegerValue(this._registerB)?
1:0]):"FCMPE"===a.operand?this._registerR=new Uint32Array([this.getFloatingPointValue(this._registerA)==this.getFloatingPointValue(this._registerB)?1:0]):"FCMPNE"===a.operand?this._registerR=new Uint32Array([this.getFloatingPointValue(this._registerA)!=this.getFloatingPointValue(this._registerB)?1:0]):"FCMPGT"===a.operand?this._registerR=new Uint32Array([this.getFloatingPointValue(this._registerA)>this.getFloatingPointValue(this._registerB)?1:0]):"FCMPGTE"===a.operand?this._registerR=new Uint32Array([this.getFloatingPointValue(this._registerA)>=
this.getFloatingPointValue(this._registerB)?1:0]):"FCMPLT"===a.operand?this._registerR=new Uint32Array([this.getFloatingPointValue(this._registerA)<this.getFloatingPointValue(this._registerB)?1:0]):"FCMPLTE"===a.operand?this._registerR=new Uint32Array([this.getFloatingPointValue(this._registerA)<=this.getFloatingPointValue(this._registerB)?1:0]):"NEG"===a.operand?this._registerR=new Uint32Array([0!=this.getUnsignedIntegerValue(this._registerA)?0:1]):"SNEG"===a.operand?this._registerR=new Int32Array([-this.getIntegerValue(this._registerA)]):
"FNEG"===a.operand?this._registerR=new Float32Array([-this.getFloatingPointValue(this._registerA)]):"INC"===a.operand?this._registerR=new Int32Array([this.getIntegerValue(this._registerA)+1]):"DEC"===a.operand?this._registerR=new Int32Array([this.getIntegerValue(this._registerA)-1]):"FINC"===a.operand?this._registerR=new Float32Array([this.getFloatingPointValue(this._registerA)+1]):"FDEC"===a.operand?this._registerR=new Float32Array([this.getFloatingPointValue(this._registerA)-1]):"REM"===a.operand?
this._registerR=new Uint32Array([this._exports.rem(this.getUnsignedIntegerValue(this._registerA),this.getUnsignedIntegerValue(this._registerB))]):"AND"===a.operand?this._registerR=new Uint32Array([this.getUnsignedIntegerValue(this._registerA)&this.getUnsignedIntegerValue(this._registerB)]):"SHIFTL"===a.operand?this._registerR=new Uint32Array([this.getUnsignedIntegerValue(this._registerA)<<this.getUnsignedIntegerValue(this._registerB)]):"SHIFTR"===a.operand?this._registerR=new Uint32Array([this.getUnsignedIntegerValue(this._registerA)>>>
this.getUnsignedIntegerValue(this._registerB)]):"NOT"===a.operand?this._registerR=new Uint32Array([~this.getUnsignedIntegerValue(this._registerA)]):"OR"===a.operand?this._registerR=new Uint32Array([this.getUnsignedIntegerValue(this._registerA)|this.getUnsignedIntegerValue(this._registerB)]):"XOR"===a.operand?this._registerR=new Uint32Array([this.getUnsignedIntegerValue(this._registerA)^this.getUnsignedIntegerValue(this._registerB)]):"FLTOINT"===a.operand?this._registerR=new Int32Array([this.getFloatingPointValue(this._registerA)]):
"INTTOFL"===a.operand?this._registerR=new Float32Array([this.getIntegerValue(this._registerA)]):"LAND"===a.operand?this._registerR=new Uint32Array([0!=this.getUnsignedIntegerValue(this._registerA)&&0!=this.getUnsignedIntegerValue(this._registerB)?1:0]):"LOR"===a.operand?this._registerR=new Uint32Array([0!=this.getUnsignedIntegerValue(this._registerA)||0!=this.getUnsignedIntegerValue(this._registerB)?1:0]):a.error(e.Operand,"Unknown operand for COMPUTE-like instruction.")}interpretSTORE(a){if("QADD"===
a.operand||"QSUB"===a.operand){var c=this.getNumericValue(a,e.Arg0),d=this.getNumericValue(a,e.Arg1),b=this._exports.add;"QSUB"===a.operand&&(b=this._exports.sub);this._registerR=new Int32Array([b(this.getIntegerValue(c),this.getIntegerValue(d))])}else"QLADD"===a.operand||"QLSUB"===a.operand?(c=this.getMemoryValue(a,e.Arg0),d=this.getNumericValue(a,e.Arg1),b=this._exports.add,"QLSUB"===a.operand&&(b=this._exports.sub),this._registerR=new Int32Array([b(this.getIntegerValue(c),this.getIntegerValue(d))])):
"STORE"===a.operand||"QSTORE"===a.operand?this.setMemoryValue(a,e.Arg1,e.Arg0):a.error(e.Operand,"Unknown operand for STORE-like instruction.")}interpretSPECIAL(a){if("TICK"===a.operand)this._registerR=new Uint32Array([this._ticks]);else if("RAND"===a.operand)this._registerR=new Uint32Array([4294967295*Math.random()]);else if("GETAVB"===a.operand){var c=this.getMemoryValue(a,e.Arg0);a=this.getNumericValue(a,e.Arg1);this._registerA=c;this._registerB=a}else"PRINT"==a.operand?(c=new String,a.arg0?c+=
decodeURI(a.arg0):c+=this.popValue(a).toString(),this._output(c.toString())):a.error(e.Operand,"Unknown operand for SPECIAL-like instruction.")}};(function(a){a[a.Operand=0]="Operand";a[a.Arg0=1]="Arg0";a[a.Arg1=2]="Arg1"})(e||={});class v{constructor(a,c){this.address=a;this.lineNumber=c}}class n{constructor(a,c){this._instruction=a;this._lineNumber=c;this._instructionParts=a.split(" ")}get lineNumber(){return this._lineNumber}error(a,c){switch(a){case e.Operand:return this.generateError(this._instruction,
this._lineNumber,0,this._instructionParts[0].length-1,c);case e.Arg0:return this.generateError(this._instruction,this._lineNumber,this._instructionParts[0].length+1,this._instructionParts[1].length-1,c);case e.Arg1:return this.generateError(this._instruction,this._lineNumber,this._instructionParts[0].length+this._instructionParts[1].length+2,this._instructionParts[2].length-1,c)}}generateError(a,c,d,b,g){let f=String();f=f+`line ${c+1}: ${g}\n`+`\t${a}\n`;f+="\t";for(a=0;a<d;a++)f+=" ";f+="^";for(d=
0;d<b;d++)f+="~";return f+="\n",Error(f)}get operand(){return 1<=this._instructionParts.length?this._instructionParts[0]:void 0}get arg0(){return 2<=this._instructionParts.length?this._instructionParts[1]:void 0}get arg1(){return 3<=this._instructionParts.length?this._instructionParts[2]:void 0}get length(){return this._instructionParts.length}}}})[726](0,p);Interpreter=p.default})();
